#!/bin/bash

# Dump ASTs of passing tests, for diff'ing with the source files later.

tmpdir=tmp-test-output
testdir=tests/passing

rm -rf "$tmpdir"
mkdir -p "$tmpdir"

for f in `ls "$testdir"`; do
    echo "$f"
    java -jar dist/compiler488.jar -D a -X "$testdir/$f" > "$tmpdir/$f"
done
