#!/bin/bash

# View diffs of expected and actual output.

expected=../tests/expected_output
actual=tmp-test-output

for f in `ls "$expected"`; do
    # If the files differ, show me.
    if ! diff "$expected/$f" "$actual/$f" > /dev/null; then
        vimdiff "$expected/$f" "$actual/$f"
    fi
done
