#!/bin/bash

# Dump ASTs of passing tests, for diff'ing with the source files later.

rm -rf tmp
mkdir -p tmp

testdir=tests/ast

for f in `ls "$testdir"`; do
    echo "$f"
    java -jar dist/compiler488.jar -D a -X "$testdir/$f" > "tmp/$f"
done
