#!/bin/bash

testdir=tests/failing

echo Syntax errors:
echo
for f in `ls $testdir | grep 'syntax_error_*'`; do
    echo "$f"
    java -jar dist/compiler488.jar -X "$testdir/$f"
    echo
done
echo
echo

echo Semantic errors:
for f in `ls $testdir | grep 'semantic_error_*'`; do
    echo "$f"
    echo "$f"
    java -jar dist/compiler488.jar -X "$testdir/$f"
    echo
done
